events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    # Performance optimization: Enable connection reuse to avoid TCP handshake overhead
    proxy_http_version 1.1;
    proxy_set_header Connection "";

    # Upstream pointing to your decoupled Auth Service container
    upstream auth_server {
        server auth_service:8000;
        keepalive 32;
    }

    server {
        listen 80;
        server_name 80.225.231.106;

        # Standard modern proxy headers
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
   

        # ----------------------------------------------------------------------
        # PUBLIC AUTH ROUTES (No authentication required to hit these)
        # ----------------------------------------------------------------------
        location / {
            proxy_pass http://auth_server;

        }

        location /api/auth/ {
            proxy_pass http://auth_server;
        }

        location /api/users/ {
            proxy_pass http://auth_server;
        }

        # ----------------------------------------------------------------------
        # INTERNAL VALIDATION ENDPOINT (Hidden from public access)
        # ----------------------------------------------------------------------
        # NGINX intercepts protected traffic and calls this internally first
        location = /api/auth/validate {
            internal;
            proxy_pass http://auth_server/api/auth/validate;
            
            proxy_pass_request_body off;
            proxy_set_header Content-Length "";
            proxy_set_header X-Original-URI $request_uri;
        }

        # ----------------------------------------------------------------------
        # PROTECTED EXTERNAL APP ROUTES (Triggers Auth Check before forwarding)
        # ----------------------------------------------------------------------
        # location /api/app-one/ {
        #     # Step A: Validate token against auth service first
        #     auth_request /api/auth/validate;

        #     # Step B: If 200 OK, forward to your external server domain/IP
        #     proxy_pass https://app-one-backend.different-domain.com/;
        # }
     }
}