events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    # Performance optimization: Enable connection reuse to avoid TCP handshake overhead
    proxy_http_version 1.1;
    proxy_set_header Connection "";

    # Upstream pointing to your decoupled Auth Service container
    upstream auth_server {
        server auth_service:8000;
        keepalive 32;
    }

    server {
        listen 80;
        server_name demonvoid.duckdns.org;
        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl;
        server_name demonvoid.duckdns.org;

        # listen 80;
        # server_name localhost;

        # Let's Encrypt SSL Certificates (Mounted from the host machine via Docker volumes)
        ssl_certificate     /etc/letsencrypt/live/demonvoid.duckdns.org/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/demonvoid.duckdns.org/privkey.pem;

        # Modern SSL protocol security optimizations
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers HIGH:!aNULL:!MD5;
        ssl_prefer_server_ciphers on;

        # Standard modern proxy headers
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
   

        location / {
            proxy_pass http://auth_server;
        }

        location /api/v1/auth/ {
            proxy_pass http://auth_server;
        }

        location /api/v1/users/ {
            auth_request /auth/verify;

            # Capture Header from the Auth Service Response
            auth_request_set $user_id $upstream_http_x_user_id;

            # Inject them to the req going to final backend
            proxy_set_header X-User-Id $user_id;

            proxy_pass http://auth_server;
        }
      

        location = /auth/verify {
            internal;

            proxy_pass http://auth_server/api/v1/auth/verify;

            proxy_pass_request_body off; 
            proxy_set_header Content-Length "";
            proxy_set_header X-Original-URI $request_uri;
        }
     }
}